name: mobility
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pylint
  - cudatoolkit
  - cudnn
  - tensorflow-gpu
  - geopy
  - joblib
  - plotly
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - black
  - numpy=1.19.5
  - python-dotenv
  - geohash2
